import os
import tkinter as tk
from tkinter import messagebox
from PIL import Image, ImageTk

# --- TACTICAL CONFIGURATION ---
INPUT_FILE = "Anizay_Map_LOD1_FLIPPED.jpg" # Map generated by the first script
OUTPUT_FILE = "Anizay_FINAL_HD_10240px.jpg"
TARGET_SIZE = 10240 # Your exact target dimension in pixels/meters

# --- MICRO-CALIBRATION (Sniper Offset) ---
# Adjust these values to align the map perfectly with game coordinates
OFFSET_NORTH = 10  # Moves the crop box UP by X original pixels
OFFSET_EAST = 10   # Moves the crop box RIGHT by X original pixels
# ------------------------------

def ultimate_crop_resize_offset():
    print(f"--- OPERATION: CROP + HD RESIZE WITH OFFSET (+{OFFSET_NORTH}N, +{OFFSET_EAST}E) ---")
    
    if not os.path.exists(INPUT_FILE):
        print(f"ERROR: Cannot find file {INPUT_FILE}.")
        return

    print("Loading massive file into RAM...")
    Image.MAX_IMAGE_PIXELS = None
    orig_img = Image.open(INPUT_FILE)
    orig_w, orig_h = orig_img.size

    print("Generating targeting radar...")
    display_size = 800
    thumb = orig_img.copy()
    thumb.thumbnail((display_size, display_size))
    thumb_w, thumb_h = thumb.size

    ratio = orig_w / thumb_w

    root = tk.Tk()
    root.title(f"Select Area - Offset (+{OFFSET_NORTH}N, +{OFFSET_EAST}E) applied automatically on click")
    
    canvas = tk.Canvas(root, width=thumb_w, height=thumb_h, cursor="crosshair")
    canvas.pack()

    tk_img = ImageTk.PhotoImage(thumb)
    canvas.create_image(0, 0, anchor=tk.NW, image=tk_img)

    rect_id = canvas.create_rectangle(0, 0, 0, 0, outline="red", width=3)

    def on_motion(event):
        # Draw red box anchored to bottom-left
        x = max(1, min(event.x, thumb_w))
        canvas.coords(rect_id, 0, thumb_h - x, x, thumb_h)

    def on_click(event):
        x = max(1, min(event.x, thumb_w))
        real_side = int(x * ratio)
        
        msg = f"Applying Calibration: NORTH +{OFFSET_NORTH}px, EAST +{OFFSET_EAST}px.\n\nProceed with crop and HD resize?"
        if messagebox.askyesno("Confirm Fire", msg):
            root.destroy()
            print(f"\n[1/2] Calculating modified coordinates and performing surgical crop...")
            
            # --- THE OFFSET MATH ---
            left = 0 + OFFSET_EAST
            bottom = orig_h - OFFSET_NORTH
            right = real_side + OFFSET_EAST
            top = (orig_h - real_side) - OFFSET_NORTH
            
            # Safety boundaries to stay inside the image
            if top < 0: top = 0
            if right > orig_w: right = orig_w

            cropped = orig_img.crop((left, top, right, bottom))
            
            print(f"[2/2] Compressing to Ultra-HD at {TARGET_SIZE}x{TARGET_SIZE}px...")
            try:
                resample_filter = Image.Resampling.LANCZOS
            except AttributeError:
                resample_filter = Image.LANCZOS

            final_img = cropped.resize((TARGET_SIZE, TARGET_SIZE), resample_filter)
            
            print(f"Saving final asset: {OUTPUT_FILE}...")
            final_img.save(OUTPUT_FILE, "JPEG", quality=95, optimize=True)
            print("--- MISSION ACCOMPLISHED: CALIBRATED ASSET READY ---")

    canvas.bind("<Motion>", on_motion)
    canvas.bind("<Button-1>", on_click)
    
    print("\n[!] Window open. Move mouse to expand the red square.")
    print("[!] Cover the playable landmass. The script handles the N/E offset automatically.")
    print("[!] Click to confirm.")
    root.mainloop()

if __name__ == "__main__":
    ultimate_crop_resize_offset()